substitutions:
  _REGION: us-central1
  _ZONE: us-central1-f

  _ENV: dev
  _NAME_PREFIX: ob

  _REPO: ob-dev-docker
  _CLUSTER: ob-dev-gke
  _NAMESPACE: default
  _DEPLOYMENT: frontend
  _CONTAINER: server

steps:
  # 1️⃣ Build image
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/frontend:$SHORT_SHA
      - services/frontend

  # 2️⃣ Push image
  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/frontend:$SHORT_SHA

  # 3️⃣ Get GKE credentials
  - name: gcr.io/cloud-builders/gcloud
    id: get-creds
    args:
      - container
      - clusters
      - get-credentials
      - ${_CLUSTER}
      - --zone=${_ZONE}
      - --project=$PROJECT_ID

  # 4️⃣ Deploy image
  - name: gcr.io/cloud-builders/kubectl
    id: deploy
    env:
      - CLOUDSDK_COMPUTE_ZONE=${_ZONE}
      - CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}
    args:
      - set
      - image
      - deployment/${_DEPLOYMENT}
      - ${_CONTAINER}=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/frontend:$SHORT_SHA
      - -n
      - ${_NAMESPACE}

  # 5️⃣ Rollout check
  - name: gcr.io/cloud-builders/kubectl
    id: rollout
    args:
      - rollout
      - status
      - deployment/${_DEPLOYMENT}
      - -n
      - ${_NAMESPACE}

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/frontend:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
