substitutions:
  _PROJECT_ID: metal-arc-481413-g9
  _REGION: us-west1
  _ZONE: us-west1-b
  _ADMIN_CIDR: "80.200.117.55/32"   # your IP

steps:
  # 1️⃣ Terraform init
  - name: hashicorp/terraform:1.6.6
    id: tf-init
    dir: terraform
    entrypoint: sh
    args:
      - -c
      - |
        terraform init -input=false

  # 2️⃣ Terraform validate
  - name: hashicorp/terraform:1.6.6
    id: tf-validate
    dir: terraform
    entrypoint: sh
    args:
      - -c
      - |
        terraform validate

  # 3️⃣ Terraform plan
  - name: hashicorp/terraform:1.6.6
    id: tf-plan
    dir: terraform
    entrypoint: sh
    args:
      - -c
      - |
        terraform plan \
          -input=false \
          -out=tfplan \
          -var="project_id=${_PROJECT_ID}" \
          -var="region=${_REGION}" \
          -var="zone=${_ZONE}" \
          -var="admin_cidr=${_ADMIN_CIDR}"

  # 4️⃣ Terraform apply
  - name: hashicorp/terraform:1.6.6
    id: tf-apply
    dir: terraform
    entrypoint: sh
    args:
      - -c
      - |
        terraform apply \
          -input=false \
          -auto-approve \
          tfplan

options:
  logging: CLOUD_LOGGING_ONLY
