substitutions:
  _PROJECT_ID: metal-arc-481413-g9
  _ZONE: us-west1-b
  _ADMIN_CIDR: "0.0.0.0/0"   # allow Cloud Build access to GKE control plane

steps:
  # 1️⃣ Terraform init
  - name: hashicorp/terraform:1.6.6
    id: tf-init
    dir: terraform
    entrypoint: sh
    args:
      - -c
      - |
        terraform init -input=false

  # 2️⃣ Terraform validate
  - name: hashicorp/terraform:1.6.6
    id: tf-validate
    dir: terraform
    entrypoint: sh
    args:
      - -c
      - |
        terraform validate

  # 3️⃣ Terraform plan (SCOPED)
  - name: hashicorp/terraform:1.6.6
    id: tf-plan
    dir: terraform
    entrypoint: sh
    args:
      - -c
      - |
        terraform plan \
          -input=false \
          -out=tfplan \
          -var="project_id=${_PROJECT_ID}" \
          -var="zone=${_ZONE}" \
          -var="admin_cidr=${_ADMIN_CIDR}" \
          -target=google_artifact_registry_repository.frontend_repo \

  # 4️⃣ Terraform apply
  - name: hashicorp/terraform:1.6.6
    id: tf-apply
    dir: terraform
    entrypoint: sh
    args:
      - -c
      - |
        terraform apply \
          -input=false \
          -auto-approve \
          tfplan

options:
  logging: CLOUD_LOGGING_ONLY
